1. Data Pre-processing step
2. Fitting Logistic Regression to the Training set
3. Predicting the test result
4. Test accuracy of the result(Creation of Confusion matrix)
5. Visualizing the test set result.


In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('C:/Users/ashly/Downloads/archive (4)/User_Data.csv',index_col=0)
df

Gender  Age  EstimatedSalary  Purchased
User ID                                          
15624510    Male   19            19000          0
15810944    Male   35            20000          0
15668575  Female   26            43000          0
15603246  Female   27            57000          0
15804002    Male   19            76000          0
...          ...  ...              ...        ...
15691863  Female   46            41000          1
15706071    Male   51            23000          1
15654296  Female   50            20000          1
15755018    Male   36            33000          0
15594041  Female   49            36000          1

[400 rows x 4 columns]

In [18]:
x=df.iloc[:,[1,2]].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [20]:
y=df.iloc[:,3].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)


In [30]:
print("x train",x_train)
print("y train",y_train)

x train [[    33  51000]
 [    27  90000]
 [    23  82000]
 [    45  26000]
 [    30 116000]
 [    31  18000]
 [    42 104000]
 [    37  74000]
 [    40  78000]
 [    25  22000]
 [    36  54000]
 [    37  78000]
 [    41  63000]
 [    42  80000]
 [    35 147000]
 [    28  87000]
 [    30 135000]
 [    30  62000]
 [    35  20000]
 [    49  36000]
 [    60 102000]
 [    50  88000]
 [    38  59000]
 [    37  93000]
 [    28  89000]
 [    34  72000]
 [    19  21000]
 [    38 112000]
 [    47  50000]
 [    59 143000]
 [    38  51000]
 [    47 144000]
 [    38  61000]
 [    36  50000]
 [    42  54000]
 [    31  58000]
 [    58  38000]
 [    31  66000]
 [    35  88000]
 [    19  70000]
 [    33 149000]
 [    28  79000]
 [    40  57000]
 [    49  28000]
 [    40 107000]
 [    27  88000]
 [    41  59000]
 [    27  20000]
 [    27  84000]
 [    42 149000]
 [    47  20000]
 [    39  71000]
 [    26  32000]
 [    38  65000]
 [    51 134000]
 [    42  64000]
 [    33  60000]
 [    29  83000]
 [    

In [28]:
print("x test",x_test)
print("y test",y_test)

x test [[    39  75000]
 [    38  61000]
 [    50  44000]
 [    48  90000]
 [    33  31000]
 [    50  88000]
 [    34 112000]
 [    23  63000]
 [    36  54000]
 [    47 144000]
 [    28  44000]
 [    42  75000]
 [    41  72000]
 [    40  60000]
 [    47  25000]
 [    19  21000]
 [    36  50000]
 [    46  32000]
 [    26  72000]
 [    28  55000]
 [    39  61000]
 [    46  23000]
 [    40  75000]
 [    60 108000]
 [    41  60000]
 [    31  15000]
 [    52  21000]
 [    27  57000]
 [    34  25000]
 [    32 135000]
 [    43 129000]
 [    35 147000]
 [    44  39000]
 [    33  43000]
 [    36 125000]
 [    39  79000]
 [    35  44000]
 [    60  42000]
 [    48  30000]
 [    35  72000]
 [    46  59000]
 [    28 123000]
 [    45  45000]
 [    39  42000]
 [    39 134000]
 [    56 133000]
 [    30 116000]
 [    22  55000]
 [    48  29000]
 [    48  33000]
 [    40  59000]
 [    36 144000]
 [    24  84000]
 [    46  88000]
 [    57  60000]
 [    58 144000]
 [    39  77000]
 [    50  36000]
 [    2

In [32]:
from sklearn.preprocessing import StandardScaler
st_x=StandardScaler()
x_train=st_x.fit_transform(x_train)

print("x train",x_train)


x train [[-3.86141100e-01 -5.21248114e-01]
 [-9.62949383e-01  6.01469657e-01]
 [-1.34748824e+00  3.71168576e-01]
 [ 7.67475465e-01 -1.24093899e+00]
 [-6.74545241e-01  1.34994817e+00]
 [-5.78410528e-01 -1.47124007e+00]
 [ 4.79071324e-01  1.00449655e+00]
 [-1.60224523e-03  1.40867495e-01]
 [ 2.86801896e-01  2.56018035e-01]
 [-1.15521881e+00 -1.35608953e+00]
 [-9.77369590e-02 -4.34885209e-01]
 [-1.60224523e-03  2.56018035e-01]
 [ 3.82936610e-01 -1.75796492e-01]
 [ 4.79071324e-01  3.13593306e-01]
 [-1.93871673e-01  2.24236486e+00]
 [-8.66814669e-01  5.15106752e-01]
 [-6.74545241e-01  1.89691324e+00]
 [-6.74545241e-01 -2.04584127e-01]
 [-1.93871673e-01 -1.41366480e+00]
 [ 1.15201432e+00 -9.53062642e-01]
 [ 2.20949617e+00  9.46921280e-01]
 [ 1.24814903e+00  5.43894387e-01]
 [ 9.45324685e-02 -2.90947033e-01]
 [-1.60224523e-03  6.87832563e-01]
 [-8.66814669e-01  5.72682022e-01]
 [-2.90006386e-01  8.32922244e-02]
 [-1.73202709e+00 -1.38487717e+00]
 [ 9.45324685e-02  1.23479763e+00]
 [ 9.5974489

fittng  logistic regression to the training set


In [33]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

predict the test result

In [35]:
y_pred=classifier.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [42]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)
cm


array([[ 0, 58],
       [ 0, 42]], dtype=int64)

In [43]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the Iris dataset
iris = load_iris()

# Split the dataset into features (X) and labels (y)
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
model = LogisticRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 1.0


C:\Users\ashly\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
